#!/bin/zsh

APP_DIR="/Users/takahata/Documents/New project"
cd "$APP_DIR" || exit 1

URL="http://127.0.0.1:5173/"

if ! lsof -nP -iTCP:5173 -sTCP:LISTEN >/dev/null 2>&1; then
  /usr/local/bin/npm run dev -- --host 127.0.0.1 --port 5173 > /tmp/michiene-ss-service-master.log 2>&1 &
  sleep 2
fi

open "$URL"
